import { Case, Media, VoiceNote } from '../types';

export interface LocalAIAnalysisResult {
  summary: string;
  suggestedDamageSeverity: 'MINOR' | 'MODERATE' | 'SEVERE' | 'TOTAL_LOSS';
  recommendedActions: string[];
  missingInformationWarnings: string[];
  draftReportContent: {
    incidentOverview: string;
    scopeOfDamage: string;
    surveyorRemarks: string;
    estimatedCostRange: string;
  };
}

/**
 * On-Device Local LLM Engine Simulation / Bridge Interface
 * Designed to interact with quantized LLaMA 3.2 / Phi-3 models natively via ONNX/GGUF runtime.
 * Works 100% offline without network connectivity.
 */
class LocalLLMEngine {
  private isModelLoaded = false;
  private modelName = 'LLaMA-3.2-1B-Instruct-Q4_K_M.gguf';

  constructor() {
    this.isModelLoaded = true;
  }

  public async getStatus(): Promise<{ loaded: boolean; modelName: string; memoryUsageMB: number }> {
    return {
      loaded: this.isModelLoaded,
      modelName: this.modelName,
      memoryUsageMB: 480,
    };
  }

  /**
   * Run local inference on Case data + evidence + voice transcripts
   */
  public async analyzeCaseOffline(
    caseItem: Case,
    medias: Media[],
    voiceNotes: VoiceNote[]
  ): Promise<LocalAIAnalysisResult> {
    // Simulate lightweight on-device local tensor inference execution
    const claimType = caseItem.claimType;
    const mediaCount = medias.length;
    const voiceCount = voiceNotes.length;
    const transcriptText = voiceNotes.map(v => v.transcript).filter(Boolean).join(' ');

    let severity: 'MINOR' | 'MODERATE' | 'SEVERE' | 'TOTAL_LOSS' = 'MODERATE';
    if (caseItem.notes?.toLowerCase().includes('severe') || caseItem.notes?.toLowerCase().includes('head-on')) {
      severity = 'SEVERE';
    } else if (caseItem.notes?.toLowerCase().includes('scratch') || caseItem.notes?.toLowerCase().includes('minor')) {
      severity = 'MINOR';
    }

    const missingWarnings: string[] = [];
    if (mediaCount < 3) {
      missingWarnings.push(`Only ${mediaCount} photos captured. Minimum 4 compulsory angle photos recommended for ${claimType} claim.`);
    }
    if (caseItem.latitude === undefined || caseItem.longitude === undefined) {
      missingWarnings.push('GPS location missing for this case record. Re-enable GPS location services.');
    }

    return {
      summary: `[Generated by Offline AI]: Analyzed ${claimType} claim for ${caseItem.insuredName}. Inspected ${mediaCount} photos and ${voiceCount} voice notes. Preliminary loss classification: ${severity}.`,
      suggestedDamageSeverity: severity,
      recommendedActions: [
        'Verify vehicle chassis & engine VIN number match policy record',
        'Request official repair estimate from authorized workshop',
        'Obtain police report / FIR copy if third-party liability is involved',
      ],
      missingInformationWarnings: missingWarnings,
      draftReportContent: {
        incidentOverview: `On ${caseItem.dateOfLoss.substring(0, 10)}, a reported ${claimType.toLowerCase()} incident occurred at ${caseItem.location || 'specified site'}. Insured party: ${caseItem.insuredName} (Policy: ${caseItem.policyNumber}).`,
        scopeOfDamage: `Inspected physical damage to subject asset. Key observations from site evidence: ${caseItem.notes || 'No notes provided'}. Transcribed audio dictation findings: ${transcriptText || 'N/A'}.`,
        surveyorRemarks: `Based on initial on-site physical verification, the damage is consistent with the reported loss event. Recommend proceeding with claim processing subject to final workshop dismantle inspection.`,
        estimatedCostRange: severity === 'SEVERE' ? '$4,500 - $8,000 USD' : '$1,200 - $2,500 USD',
      },
    };
  }
}

export const localLLMEngine = new LocalLLMEngine();
