import { Case, Media, VoiceNote, SyncQueueItem } from '../types';
import { toMediaDeletePayload, toMediaDeltaPayload } from '../services/SyncPayloads';

/**
 * RealmManager provides a reactive offline-first data manager layer.
 * Manages local case cache, evidence files, and offline mutation queues.
 */
class RealmManager {
  private localCases: Map<string, Case> = new Map();
  private localMedias: Map<string, Media[]> = new Map();
  private localVoiceNotes: Map<string, VoiceNote[]> = new Map();
  private syncQueue: SyncQueueItem[] = [];

  constructor() {
    this.seedMockOfflineData();
  }

  private seedMockOfflineData() {
    const mockCase: Case = {
      id: '11111111-1111-4111-8111-111111111101',
      organizationId: '00000000-0000-0000-0000-000000000001',
      caseNumber: 'CAS-2026-MOTOR-0891',
      claimType: 'MOTOR',
      policyNumber: 'POL-9923812',
      insuredName: 'Robert Davis',
      insuredContact: '+1 (555) 234-5678',
      location: 'Market St & 4th St, San Francisco, CA',
      latitude: 37.7749,
      longitude: -122.4194,
      dateOfLoss: new Date(Date.now() - 48 * 3600000).toISOString(),
      assignedDate: new Date(Date.now() - 24 * 3600000).toISOString(),
      priority: 'HIGH',
      status: 'IN_PROGRESS',
      syncStatus: 'OFFLINE_ONLY',
      checklistData: JSON.stringify({
        odometer: '45,210 miles',
        point_of_impact: 'Front bumper & radiator grill',
        airbags_deployed: true,
        drivable: false,
      }),
      notes: 'Front bumper severely damaged. Radiator leak detected on-site.',
      aiSummary: '[Generated by Offline AI]: Frontal impact resulting in radiator compromise and bumper dislocation. Estimated severe structural assessment required.',
      createdAt: new Date(Date.now() - 24 * 3600000).toISOString(),
      updatedAt: new Date().toISOString(),
    };

    this.localCases.set(mockCase.id, mockCase);

    // Evidence is intentionally not seeded: the gallery renders real files from disk,
    // so a placeholder path would surface as a broken image tile.
    this.localMedias.set(mockCase.id, []);
  }

  // Cases
  public async getCases(): Promise<Case[]> {
    return Array.from(this.localCases.values());
  }

  public async getCaseById(id: string): Promise<Case | undefined> {
    return this.localCases.get(id);
  }

  public async saveCase(caseItem: Case): Promise<Case> {
    const isNew = !this.localCases.has(caseItem.id);
    this.localCases.set(caseItem.id, caseItem);

    // Enqueue for offline sync
    this.enqueueSync({
      id: `queue-${Date.now()}-${Math.random().toString(36).substring(2, 7)}`,
      entityName: 'case',
      entityId: caseItem.id,
      action: isNew ? 'CREATE' : 'UPDATE',
      payloadJson: JSON.stringify(caseItem),
      createdAt: new Date().toISOString(),
      retryCount: 0,
    });

    return caseItem;
  }

  // Media
  /** Live evidence for a case, newest last. Soft-deleted items are excluded. */
  public async getMediaForCase(caseId: string): Promise<Media[]> {
    return (this.localMedias.get(caseId) || []).filter(m => !m.isDeleted);
  }

  public async getMediaById(caseId: string, mediaId: string): Promise<Media | undefined> {
    return (this.localMedias.get(caseId) || []).find(m => m.id === mediaId);
  }

  public async saveMedia(media: Media): Promise<Media> {
    const list = this.localMedias.get(media.caseId) || [];
    const existingIndex = list.findIndex(m => m.id === media.id);
    const isNew = existingIndex === -1;

    const record: Media = { ...media, updatedAt: new Date().toISOString() };
    if (isNew) {
      list.push(record);
    } else {
      list[existingIndex] = record;
    }
    this.localMedias.set(media.caseId, list);

    this.enqueueSync({
      id: `queue-${Date.now()}-${Math.random().toString(36).substring(2, 7)}`,
      entityName: 'media',
      entityId: record.id,
      action: isNew ? 'CREATE' : 'UPDATE',
      payloadJson: JSON.stringify(toMediaDeltaPayload(record)),
      createdAt: new Date().toISOString(),
      retryCount: 0,
    });

    return record;
  }

  /**
   * Soft-deletes evidence so the removal still propagates to the server on the next
   * delta flush. Callers are responsible for unlinking the underlying image files.
   */
  public async deleteMedia(caseId: string, mediaId: string): Promise<Media | undefined> {
    const list = this.localMedias.get(caseId) || [];
    const target = list.find(m => m.id === mediaId);
    if (!target) return undefined;

    target.isDeleted = true;
    target.updatedAt = new Date().toISOString();
    this.localMedias.set(caseId, list);

    this.enqueueSync({
      id: `queue-${Date.now()}-${Math.random().toString(36).substring(2, 7)}`,
      entityName: 'media',
      entityId: mediaId,
      action: 'DELETE',
      payloadJson: JSON.stringify(toMediaDeletePayload(mediaId, caseId)),
      createdAt: new Date().toISOString(),
      retryCount: 0,
    });

    return target;
  }

  // Voice Notes
  public async getVoiceNotesForCase(caseId: string): Promise<VoiceNote[]> {
    return this.localVoiceNotes.get(caseId) || [];
  }

  public async saveVoiceNote(note: VoiceNote): Promise<VoiceNote> {
    const list = this.localVoiceNotes.get(note.caseId) || [];
    list.push(note);
    this.localVoiceNotes.set(note.caseId, list);
    return note;
  }

  // Sync Queue
  public enqueueSync(item: SyncQueueItem): void {
    this.syncQueue.push(item);
  }

  public getSyncQueue(): SyncQueueItem[] {
    return [...this.syncQueue];
  }

  public clearSyncQueue(): void {
    this.syncQueue = [];
  }
}

export const realmManager = new RealmManager();
